apiVersion: aws.kubeform.com/v1alpha1
kind: DbInstance
metadata:
  name: test1
spec:
  allocatedStorage: 5
  storageType: gp2
  engine: mysql
  engineVersion: "5.7"
  skipFinalSnapshot: true
  dbSubnetGroupName: "mcmains-db-subnet"
  instanceClass: db.t2.micro
  name: mydb
  username: foo
  parameterGroupName: default.mysql5.7
  providerRef:
    name: aws
  secretRef:
    name: pass
